source 'https://rubygems.org'

gem 'rails', '4.0.0.beta1'

gem 'sqlite3'

group :assets do
  gem 'sass-rails',   '~> 4.0.0.beta1'
  gem 'coffee-rails', '~> 4.0.0.beta1'

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

gem 'turbolinks'

gem 'jbuilder', '~> 1.0.1'

gem 'pry-rails'
gem 'pry-debugger'
